import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "VeraDial Privacy Policy — how we collect, use, and protect your data.",
};

export default function PrivacyPage() {
  return (
    <article className="mx-auto max-w-[720px] px-6 pb-24 pt-32">
      <h1 className="font-display text-4xl font-bold">Privacy Policy</h1>
      <p className="mt-2 text-sm text-text-muted">Last updated: March 25, 2026</p>

      <div className="mt-12 space-y-10 text-sm leading-relaxed text-text-secondary">
        <section>
          <h2 className="font-display text-xl font-semibold text-text-primary">
            1. Information We Collect
          </h2>
          <div className="mt-4 space-y-3">
            <p>
              <strong className="text-text-primary">Account data:</strong> When you create
              an account, we collect your email address and profile information through
              Supabase Auth.
            </p>
            <p>
              <strong className="text-text-primary">Caller profile:</strong> If you use AI
              Calling, we store your display name, website, and caller context that you
              provide. These are used to identify you on AI calls and voicemail greetings.
            </p>
            <p>
              <strong className="text-text-primary">Phone numbers:</strong> We store
              information about your purchased phone numbers (including Twilio SID,
              capabilities, region, and country) and any verified caller IDs you add.
            </p>
            <p>
              <strong className="text-text-primary">Call records:</strong> We maintain call
              logs including from/to numbers, duration, timestamps, voice effect used, and
              Twilio call SID for your account history.
            </p>
            <p>
              <strong className="text-text-primary">Call transcripts:</strong> When you
              record an outbound call, the audio is automatically sent to a third-party
              speech recognition service (Deepgram) for transcription. We store structured
              transcripts including speaker identification, text, and timestamps alongside
              the call record.
            </p>
            <p>
              <strong className="text-text-primary">Call screening data:</strong> When call
              screening is enabled, we store the screening interaction data including the
              caller&apos;s stated identity and intent, a conversation identifier, and
              timestamp.
            </p>
            <p>
              <strong className="text-text-primary">SMS content:</strong> We store message
              bodies, sender/recipient numbers, timestamps, and delivery status for
              messages sent and received through the service.
            </p>
            <p>
              <strong className="text-text-primary">Consent records:</strong> We maintain
              SMS consent status and timestamps to comply with telecommunications
              regulations.
            </p>
            <p>
              <strong className="text-text-primary">Voicemail:</strong> We store voicemail
              recordings, transcriptions, duration, and caller information for voicemails
              left on your VeraDial number. Voicemail audio is recorded and transcribed by
              Twilio.
            </p>
            <p>
              <strong className="text-text-primary">Voicemail greetings:</strong> If you
              create a custom voicemail greeting, we store the greeting text you write, the
              voice you select, and the generated audio file. Audio is generated by a
              third-party AI provider (ElevenLabs) and stored in cloud storage (Supabase
              Storage).
            </p>
            <p>
              <strong className="text-text-primary">AI Call data:</strong> When you use AI
              Call, we store the phone number called, your call goal and notes,
              call duration, and the full conversation transcript and summary generated by
              the AI agent. Call audio is processed in real-time by our AI provider and is
              not stored by VeraDial.
            </p>
            <p>
              <strong className="text-text-primary">Push notification tokens:</strong> We
              store device push tokens to deliver notifications to your device. Tokens are
              automatically deleted when you sign out or your session expires.
            </p>
            <p>
              <strong className="text-text-primary">Billing:</strong> Purchase and
              subscription history is managed through RevenueCat and the App Store. We
              store your subscription status, billing period, and credit balance. We do not
              store payment card details directly.
            </p>
          </div>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-text-primary">
            2. How We Use Your Information
          </h2>
          <ul className="mt-4 list-disc space-y-2 pl-5">
            <li>Provide calling, messaging, voicemail, and call screening services</li>
            <li>Enforce acceptable use policies and detect abuse</li>
            <li>Process STOP/HELP opt-out requests (TCPA compliance)</li>
            <li>Maintain call, message, and voicemail history for your account</li>
            <li>Transcribe recorded calls for your review</li>
            <li>Generate AI-powered phone calls on your behalf using your instructions</li>
            <li>Store transcripts and summaries of AI calls for your review</li>
            <li>Screen inbound calls and report caller identity to you</li>
            <li>Generate custom voicemail greetings from your text input</li>
            <li>
              Send push notifications for incoming messages, voicemails, missed calls, AI
              call completions, and low balance alerts
            </li>
            <li>Manage your subscription and credit balance</li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-text-primary">
            3. Third-Party Services
          </h2>
          <div className="mt-4 space-y-3">
            <p>
              <strong className="text-text-primary">Twilio:</strong> Voice calls, SMS
              delivery, phone number provisioning, and voicemail recording and
              transcription. Twilio processes call audio and message content.{" "}
              <a
                href="https://www.twilio.com/en-us/legal/privacy"
                className="text-accent hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                Twilio Privacy Policy
              </a>
            </p>
            <p>
              <strong className="text-text-primary">Supabase:</strong> Authentication,
              database hosting (US-West-2 region), and file storage for voicemail greeting
              audio.{" "}
              <a
                href="https://supabase.com/privacy"
                className="text-accent hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                Supabase Privacy Policy
              </a>
            </p>
            <p>
              <strong className="text-text-primary">RevenueCat:</strong> In-app purchase
              management and subscription tracking.{" "}
              <a
                href="https://www.revenuecat.com/privacy/"
                className="text-accent hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                RevenueCat Privacy Policy
              </a>
            </p>
            <p>
              <strong className="text-text-primary">ElevenLabs:</strong> AI voice
              processing for three features: (1) AI Call — call audio and your instructions
              are processed to generate the AI agent&apos;s responses; (2) Call
              Screening — inbound call audio is processed to identify the caller; (3)
              Voicemail Greetings — your greeting text is converted to speech audio.
              ElevenLabs receives call audio during AI calls and screening interactions.{" "}
              <a
                href="https://elevenlabs.io/privacy-policy"
                className="text-accent hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                ElevenLabs Privacy Policy
              </a>
            </p>
            <p>
              <strong className="text-text-primary">Deepgram:</strong> Speech-to-text
              transcription for recorded calls. When you record an outbound call, the audio
              is sent to Deepgram for automatic transcription.{" "}
              <a
                href="https://deepgram.com/privacy"
                className="text-accent hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                Deepgram Privacy Policy
              </a>
            </p>
            <p>
              <strong className="text-text-primary">Expo:</strong> Push notification
              delivery. Device push tokens are sent through Expo&apos;s push notification
              service, which routes them to Apple Push Notification service (APNs) or
              Firebase Cloud Messaging (FCM) for delivery to your device.{" "}
              <a
                href="https://expo.dev/privacy"
                className="text-accent hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                Expo Privacy Policy
              </a>
            </p>
            <p>
              <strong className="text-text-primary">Apple / Google:</strong> App
              distribution and payment processing via the App Store and Google Play Store.
            </p>
          </div>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-text-primary">
            4. SMS Consent &amp; Opt-Out
          </h2>
          <ul className="mt-4 list-disc space-y-2 pl-5">
            <li>
              Recipients can text <strong className="text-text-primary">STOP</strong> to
              opt out of messages from any VeraDial number.
            </li>
            <li>
              We honor <strong className="text-text-primary">HELP</strong> requests with
              support contact information.
            </li>
            <li>Opt-out records are maintained per sender/recipient pair.</li>
            <li>Consent status is checked before every outbound message.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-text-primary">
            5. Push Notifications
          </h2>
          <div className="mt-4 space-y-3">
            <p>
              VeraDial sends push notifications for incoming messages, new voicemails,
              missed calls, AI call completions, and low credit balance alerts.
            </p>
            <p>
              For your privacy, notifications display only the sender or caller
              number — no message content, voicemail transcriptions, or AI summaries
              appear on your lock screen.
            </p>
            <p>
              You can disable notifications at any time through your device&apos;s system
              settings. Push tokens are stored on our server and are automatically deleted
              when you sign out or your session expires.
            </p>
          </div>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-text-primary">
            6. Data Retention
          </h2>
          <ul className="mt-4 list-disc space-y-2 pl-5">
            <li>
              <strong className="text-text-primary">Call logs and SMS history:</strong>{" "}
              Retained for the lifetime of your account.
            </li>
            <li>
              <strong className="text-text-primary">Call transcripts:</strong>{" "}
              Retained alongside call records for the lifetime of your account.
            </li>
            <li>
              <strong className="text-text-primary">Call screening data:</strong>{" "}
              Retained with call logs for the lifetime of your account.
            </li>
            <li>
              <strong className="text-text-primary">Voicemail recordings:</strong>{" "}
              Retained for the lifetime of your account.
            </li>
            <li>
              <strong className="text-text-primary">Voicemail greetings:</strong>{" "}
              Retained until you delete them or your account is deleted.
            </li>
            <li>
              <strong className="text-text-primary">Opt-out records:</strong> Retained
              indefinitely as required for TCPA compliance.
            </li>
            <li>
              <strong className="text-text-primary">AI Call transcripts:</strong>{" "}
              Transcripts and summaries are retained for the lifetime of your account.
              Call goals and notes are stored with each AI call record.
            </li>
            <li>
              <strong className="text-text-primary">Push tokens:</strong>{" "}
              Deleted when you sign out, your session expires, or your device is no
              longer registered.
            </li>
            <li>
              <strong className="text-text-primary">Released/swapped numbers:</strong>{" "}
              Records retained with &ldquo;swapped&rdquo; or &ldquo;released&rdquo;
              status.
            </li>
            <li>
              <strong className="text-text-primary">Account deletion:</strong> Contact{" "}
              <a
                href="mailto:support@veradial.com"
                className="text-accent hover:underline"
              >
                support@veradial.com
              </a>{" "}
              to request account deletion.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-text-primary">
            7. Abuse Prevention &amp; Account Suspension
          </h2>
          <p className="mt-4">
            We monitor for patterns consistent with harassment, fraud, or illegal use.
            Accounts may be suspended or terminated for policy violations. Abuse cases are
            logged and retained.
          </p>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-text-primary">
            8. Your Rights
          </h2>
          <div className="mt-4 space-y-3">
            <p>
              <strong className="text-text-primary">California residents (CCPA):</strong>{" "}
              You have the right to know what data we collect, request deletion, and
              opt-out of the sale of personal information. We do not sell your personal
              data.
            </p>
            <p>
              <strong className="text-text-primary">EU/EEA residents (GDPR):</strong> You
              have the right to access, rectify, erase, and port your data.
            </p>
            <p>
              To exercise your rights, email{" "}
              <a
                href="mailto:support@veradial.com"
                className="text-accent hover:underline"
              >
                support@veradial.com
              </a>
              .
            </p>
          </div>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-text-primary">
            9. Emergency Services
          </h2>
          <div className="mt-4 space-y-3">
            <p>
              VeraDial is <strong className="text-text-primary">NOT</strong> a replacement
              for traditional phone service. 911 and emergency calling is not supported. Do
              not rely on VeraDial for emergency communications.
            </p>
          </div>
        </section>

        <section>
          <h2 className="font-display text-xl font-semibold text-text-primary">
            10. Contact
          </h2>
          <p className="mt-4">
            For privacy inquiries, contact us at{" "}
            <a
              href="mailto:support@veradial.com"
              className="text-accent hover:underline"
            >
              support@veradial.com
            </a>
            .
          </p>
        </section>
      </div>
    </article>
  );
}
